language: node_js
node_js: node

env:
  - ELM_VERSION=0.19.0

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - $HOME/.npm

install:
  - npm install -g elm@$ELM_VERSION 

script:
  - elm make src/Main.elm --output=bingo.js

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master


